markdown: GFM
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Digital Tutoring As A Service | SE-673
description: Project Documentation for a Digital Tutoring Platform as a service
show_downloads: false
