markdown: GFM
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
title: Digital Tutoring As A Service | SE-673 | Documentation Site
description: Documentation site for software design for a digital tutoring service
show_downloads: false
